//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub mod prelude;

pub mod note;
pub mod note_history;
pub mod note_link;
pub mod note_tags;
pub mod note_template;
pub mod notebook;
pub mod settings;
pub mod sync_log;
pub mod sync_log_detail;
pub mod tag;
