//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "note")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub notebook_id: i64,
    pub title: String,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")")]
    pub content: String,
    pub create_time: DateTime,
    pub update_time: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::notebook::Entity",
        from = "Column::NotebookId",
        to = "super::notebook::Column::Id"
    )]
    Notebook,
}

impl Related<super::notebook::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notebook.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
