//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

/// 内容类型枚举
#[derive(Clone, Copy, Debug, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "lowercase")]
pub enum ContentType {
    /// HTML 格式（默认）
    #[default]
    Html = 0,
    /// Markdown 格式
    Markdown = 1,
}

impl From<i32> for ContentType {
    fn from(value: i32) -> Self {
        match value {
            1 => ContentType::Markdown,
            _ => ContentType::Html,
        }
    }
}

impl From<ContentType> for i32 {
    fn from(value: ContentType) -> Self {
        value as i32
    }
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "note")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub notebook_id: i64,
    pub title: String,
    #[sea_orm(column_type = "custom(\"LONGTEXT\")")]
    pub content: String,
    /// 内容类型：0 = HTML，1 = Markdown
    pub content_type: i32,
    /// 是否置顶：0 = 否，1 = 是
    pub is_pinned: i32,
    /// 是否收藏/星标：0 = 否，1 = 是
    pub is_starred: i32,
    /// MCP 访问控制：0=继承, 1=读写, 2=只读, 3=禁止
    pub mcp_access: i32,
    pub create_time: DateTime,
    pub update_time: DateTime,
    /// 软删除时间，NULL 表示未删除
    pub deleted_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::notebook::Entity",
        from = "Column::NotebookId",
        to = "super::notebook::Column::Id"
    )]
    Notebook,
}

impl Related<super::notebook::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Notebook.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
