//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::category::Entity as Category;
pub use super::not_tags::Entity as NotTags;
pub use super::note::Entity as Note;
pub use super::note_history::Entity as NoteHistory;
pub use super::tag::Entity as Tag;
