//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

pub use super::note::Entity as Note;
pub use super::note_history::Entity as NoteHistory;
pub use super::note_tags::Entity as NoteTags;
pub use super::notebook::Entity as Notebook;
pub use super::tag::Entity as Tag;
