//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

#![allow(unused_imports)]

pub use super::note::Entity as Note;
pub use super::note_attachment::Entity as NoteAttachment;
pub use super::note_history::Entity as NoteHistory;
pub use super::note_link::Entity as NoteLink;
pub use super::note_tags::Entity as NoteTags;
pub use super::note_template::Entity as NoteTemplate;
pub use super::notebook::Entity as Notebook;
pub use super::settings::Entity as Settings;
pub use super::sync_log::Entity as SyncLog;
pub use super::sync_log_detail::Entity as SyncLogDetail;
pub use super::tag::Entity as Tag;
